export const REGISTER = 'REGISTER';
export const LOGIN = 'LOGIN';

export const AUTHENTICATE_START = 'AUTHENTICATE_START';
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_FAIL = 'AUTHENTICATE_FAIL';

export const SET_AUTH_STATE = 'SET_AUTH_STATE';
export const CHECK_AUTH_STATE = 'CHECK_AUTH_STATE';
export const EMPTY_AUTH_STATE = 'EMPTY_AUTH_STATE';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_END = 'LOGOUT_END';

export const AUTH_DISMISS_ERROR = 'AUTH_DISMISS_ERROR';
