export const REGISTER = 'REGISTER';
export const LOGIN = 'LOGIN';

export const AUTHENTICATE_START = 'AUTHENTICATE_START';
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_FAIL = 'AUTHENTICATE_FAIL';

export const SET_AUTH_STATE = 'SET_AUTH_STATE';
export const CHECK_AUTH_STATE = 'CHECK_AUTH_STATE';
export const EMPTY_AUTH_STATE = 'EMPTY_AUTH_STATE';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_END = 'LOGOUT_END';

export const AUTH_DISMISS_ERROR = 'AUTH_DISMISS_ERROR';

export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_START = 'CREATE_POST_START';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL';

export const GET_ALL_POSTS = 'GET_ALL_POSTS';
export const GET_ALL_POSTS_START = 'GET_ALL_POSTS_START';
export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS';
export const GET_ALL_POSTS_FAIL = 'GET_ALL_POSTS_FAIL';

export const GET_USER_POSTS = 'GET_USER_POSTS';
export const GET_USER_POSTS_START = 'GET_USER_POSTS_START';
export const GET_USER_POSTS_SUCCESS = 'GET_USER_POSTS_SUCCESS';
export const GET_USER_POSTS_FAIL = 'GET_USER_POSTS_FAIL';

export const EDIT_POST = 'EDIT_POST';
export const EDIT_POST_START = 'EDIT_POST_START';
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS';
export const EDIT_POST_FAIL = 'EDIT_POST_FAIL';

export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_START = 'DELETE_POST_START';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL';

export const TOGGLE_LIKE_POST = 'TOGGLE_LIKE_POST';
export const TOGGLE_LIKE_POST_START = 'TOGGLE_LIKE_POST_START';
export const TOGGLE_LIKE_POST_SUCCESS = 'TOGGLE_LIKE_POST_SUCCESS';
export const TOGGLE_LIKE_POST_FAIL = 'TOGGLE_LIKE_POST_FAIL';

export const DISABLE_GO_BACK = 'DISABLE_GO_BACK';

export const POSTS_DISMISS_ERROR = 'POSTS_DISMISS_ERROR';
